application: silexexample1
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: .*
  script: main.php

inbound_services:
- warmup

